name: Playwright Python Tests (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-playwright  # ensure pytest-playwright is there

    - name: Install Playwright browsers
      run: |
        python -m playwright install

    - name: Run tests
      run: pytest --headless
